### ISSUE TITLE
error in remaining lifes

### ISSUE THREAD

**Issue by pritikmshaw** [shawavisek35/word-master#4]
Technically the game should end when I have 0 lives left but that's not happening instead it is counting the lives as -1,-2, and so on

**Comment by shawavisek35** [comment]
@pritikmshaw i have assigned you for this issue.
Please do follow this guidelines before creating a pull request
Step 1 : Create an Issue.
Step 2 : Wait for me to assign it to u.
Step 3 : Work on that issue.
Step 4 : Create a pull request mentioning this issue

**Comment by pritikmshaw** [comment]
ok captain

**Comment by pritikmshaw** [comment]
solved
